Ext.define('srm.basicdata.regAccount.model.MngCompanyInfo', {
	extend: 'Ext.data.Model',
	idProperty: 'company_id',
	fields: [
		{ name: 'company_id', type: 'int' },
		{ name: 'class_id' },
		{ name: 'nature_id' },
		{ name: 'apply_sts', type: 'int' },
		{ name: 'cpyname_en' },
		{ name: 'cpyname_cn' },
		{ name: 'reg_addr_code', type: 'int' },
		{ name: 'reg_addr' },
		{ name: 'contact_addr_code', type: 'int' },
		{ name: 'industry_id', type: 'int' },
		{ name: 'contact_addr' },
		{ name: 'f_phone' },
		{ name: 'nature_name' },
		{ name: 'class_name' },
		{ name: 'industry_name' },
		{ name: 'taxman_name' },
		{ name: 'currency_name' },
		{ name: 'corporation' },
		{ name: 'contacts' },
		{ name: 'm_phone' },
		{ name: 'fax' },
		{ name: 'email' },
		{ name: 'contact_email' },
		{ name: 'bus_license' },
		{ name: 'tax_no' },
		{ name: 'reg_fund', type: 'float' },
		{ name: 'taxman_id', type: 'int' },
		{ name: 'currency_id', type: 'int' },
		{ name: 'establish_dt', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'emplyees', type: 'int' },
		{ name: 'college_num', type: 'int' },
		{ name: 'diploma_num', type: 'int' },
		{ name: 'diploma_down_num', type: 'int' },
		{ name: 'op_num', type: 'int' },
		{ name: 'tech_num', type: 'int' },
		{ name: 'qc_num', type: 'int' },
		{ name: 'staff_num', type: 'int' },
		{ name: 'internal_auditor_num', type: 'int' },
		{ name: 'qe_num', type: 'int' },
		{ name: 'factory_owner' },
		{ name: 'use_begintime', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'use_endtime', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'turnover', type: 'float' },
		{ name: 'turnover_currency_id', type: 'int' },
		{ name: 'import_num', type: 'float' },
		{ name: 'import_currency_id', type: 'int' },
		{ name: 'export_num', type: 'float' },
		{ name: 'export_currency_id', type: 'int' },
		{ name: 'certification_system' },
		{ name: 'create_dt', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'ip_addr' },
		{ name: 'checked_date', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'version', type: 'int' },
		{ name: 'lng', type: 'float' },
		{ name: 'lat', type: 'float' },
		{ name: 'quality_control', type: 'int' },
		{ name: 'key_remark' },
		{ name: 'operator' },
		{ name: 'operater_dt', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'auditor' },
		{ name: 'audit_dt', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'company_introduction' },
		{ name: 'school_coop' },
		{ name: 'is_main', type: 'int' }
	]
});
