Ext.define('srm.mngOrderManager.model.MngPurchaseOrder', {
	extend: 'Ext.data.Model',
	idProperty: 'pur_order_id',
	fields: [
		{ name: 'pur_order_id', type: 'int' },
		{ name: 'order_bh' },
		{ name: 'agreement_bh' },
		{ name: 'order_status', type: 'int' },
		{ name: 'create_dt', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'category_id', type: 'int' },
		{ name: 'category_name' },
		{ name: 'supplier_id', type: 'int' },
		{ name: 'sum_money', type: 'float' },
		{ name: 'pur_company_id', type: 'int' },
		{ name: 'pur_cpyname_cn' },
		{ name: 'pur_creator_id', type: 'int' },
		{ name: 'pur_creator_name' },
		{ name: 'invoice_title_id', type: 'int' },
		{ name: 'pur_invoice_type', type: 'int' },
		{ name: 'pur_invoice_title' },
		{ name: 'delivery_address_id', type: 'int' },
		{ name: 'pur_delivery_address' },
		{ name: 'pur_delivery_contact' },
		{ name: 'pur_delivery_contact_phone' },
		{ name: 'pur_memo' },
		{ name: 'sup_company_id', type: 'int' },
		{ name: 'sup_cpyname_cn' },
		{ name: 'sup_contact' },
		{ name: 'sup_contact_phone' },
		{ name: 'sup_contact_address' },
		{ name: 'sup_memo' },
		{ name: 'order_remark' },
		{ name: 'pur_delete_flag', type: 'int' },
		{ name: 'sup_delete_flag', type: 'int' },
		{ name: 'source_type', type: 'int' },
		{ name: 'lock_agreement', type: 'int' },
		{ name: 'delivery_date', type: 'date', dateFormat: 'Y-m-d H:i:s' }
	]
});
