Ext.define('srm.supplierManager.model.Supplier', {
	extend: 'Ext.data.Model',
	idProperty: 's_id',
	identifier:'negative',
	fields: [
		{ name: 's_id', type: 'int' },
		{ name: 's_code' },
		{ name: 's_name' },
		{ name: 'main_product' },
		{ name: 'est_date', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'reg_addr' },
		{ name: 'company_addr' },
		{ name: 'corporation' },
		{ name: 'fox' },
		{ name: 'connect_type' },
		{ name: 'tel' },
		{ name: 'contacts' },
		{ name: 'phone' },
		{ name: 'email' },
		{ name: 'nature' },
		{ name: 'trade_type' },
		{ name: 'taxpayer_type' },
		{ name: 'reg_capital', type: 'float' },
		{ name: 'establish_dt', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'emplyees', type: 'int' },
		{ name: 'business_type' },
		{ name: 'factory_area', type: 'float' },
		{ name: 'owner' },
		{ name: 'begin_dt', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'end_dt', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'brand' },
		{ name: 'customers' },
		{ name: 'competitor' },
		{ name: 'turnover', type: 'float' },
		{ name: 'company_area', type: 'float' },
		{ name: 'certification_system' },
		{ name: 'op_num', type: 'int' },
		{ name: 'tech_num', type: 'int' },
		{ name: 'qc_num', type: 'int' },
		{ name: 'staff_num', type: 'int' },
		{ name: 'college_num', type: 'int' },
		{ name: 'qe_num', type: 'int' },
		{ name: 'equipment' },
		{ name: 'material_source' },
		{ name: 'create_dt', type: 'date', dateFormat: 'Y-m-d H:i:s' },
		{ name: 'modify_dt', type: 'date', dateFormat: 'Y-m-d H:i:s' }
	]
});